# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AlyNv5nbrliYeQ6PMTtk7Pt-ZKsEe_Db

# Synthèse Vocale Wolof et Français avec SpeechT5

Ce notebook démontre l'utilisation du modèle SpeechT5 de Hugging Face pour la synthèse vocale en Wolof et en Français. Il inclut l'extraction de "speaker embeddings" pour une voix plus naturelle et l'utilisation de SSML pour contrôler la cadence.

## 1. Configuration initiale et installation des dépendances
"""

# Installer toutes les bibliothèques nécessaires
!pip install transformers datasets torch torchaudio speechbrain gdown IPython

"""### 1.1 Configuration du HF_TOKEN

Pour définir votre `HF_TOKEN` et éviter les avertissements de Hugging Face :

1.  **Obtenez un jeton (token) Hugging Face :**
    *   Rendez-vous sur [Hugging Face Settings/Tokens](https://huggingface.co/settings/tokens).
    *   Créez un nouveau jeton d'accès avec le rôle `Read` (lecture).

2.  **Ajoutez le jeton aux secrets de Colab :**
    *   Dans Colab, cliquez sur l'icône "🔑" (Secrets) dans le panneau de gauche.
    *   Cliquez sur `+ New secret`.
    *   Pour le champ `Name`, entrez `HF_TOKEN` (cela doit correspondre au nom que le code cherchera).
    *   Pour le champ `Value`, collez le jeton que vous avez copié depuis Hugging Face.
    *   Assurez-vous que l'option `Notebook access` est cochée pour ce secret.

3.  **Chargez le jeton dans votre code :**
    *   La cellule suivante montre comment charger le `HF_TOKEN` depuis les secrets de Colab. Une fois chargé, la bibliothèque `transformers` l'utilisera automatiquement pour vos requêtes.
"""

# Importe la bibliothèque pour charger les secrets Colab
from google.colab import userdata

# Charge le HF_TOKEN depuis les secrets de Colab
HF_TOKEN = userdata.get('HF_TOKEN')

# Vous pouvez maintenant utiliser HF_TOKEN directement ou la bibliothèque
# transformers le détectera automatiquement une fois qu'il sera chargé dans l'environnement.
# Si vous voulez le définir explicitement pour la session courante:
import os
os.environ['HF_TOKEN'] = HF_TOKEN

print("HF_TOKEN chargé avec succès depuis les secrets de Colab.")

"""## 2. Chargement du modèle SpeechT5 et définition de la fonction de génération"""

import torch
from transformers import SpeechT5ForTextToSpeech, SpeechT5Processor, SpeechT5HifiGan
from IPython.display import Audio, display

def load_speech_model(checkpoint="bilalfaye/speecht5_tts-wolof-v0.2", vocoder_checkpoint="microsoft/speecht5_hifigan"):
    """ Charge le modèle SpeechT5, le processeur et le vocodeur pour la synthèse vocale. """

    # Détecte automatiquement si un GPU est disponible
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

    # Charge le processeur et le modèle SpeechT5
    processor = SpeechT5Processor.from_pretrained(checkpoint)
    model = SpeechT5ForTextToSpeech.from_pretrained(checkpoint).to(device)

    # Charge le vocodeur HiFi-GAN (utilisé pour convertir les spectrogrammes en audio)
    vocoder = SpeechT5HifiGan.from_pretrained(vocoder_checkpoint).to(device)

    return processor, model, vocoder, device

# Charger les modèles globaux
processor, model, vocoder, device = load_speech_model()

# Initialiser un speaker embedding temporaire (sera mis à jour plus tard avec un embedding réel)
speaker_embedding = torch.randn(1, 512).to(device)
print("Modèles SpeechT5 chargés avec succès.")

def generate_speech_from_text(input_text, speaker_embedding, processor=processor, model=model, vocoder=vocoder, use_ssml=False):
    """ Génère de la parole à partir d'un texte d'entrée en utilisant SpeechT5 et le vocodeur HiFi-GAN.
        Si `use_ssml` est `True`, `input_text` est traité comme du SSML.
        Exemple SSML pour les pauses: `<break time=\"500ms\"/>`
    """
    # Le SpeechT5Processor tokenise le texte brut, y compris les balises SSML.
    # Le modèle les interprète ensuite.
    inputs = processor(text=input_text, return_tensors="pt", padding=True, truncation=True, max_length=model.config.max_text_positions)
    inputs = {key: value.to(model.device) for key, value in inputs.items()}

    # Génère le spectrogramme Mel à partir du texte et de l'embedding du locuteur
    speech = model.generate(
        inputs["input_ids"],
        speaker_embeddings=speaker_embedding.to(model.device),
        vocoder=vocoder,
        num_beams=7,
        temperature=0.6,
        no_repeat_ngram_size=3,
        repetition_penalty=1.5,
    )

    # Convertit le spectrogramme en audio et le lit
    speech = speech.detach().cpu().numpy()
    display(Audio(speech, rate=16000))

"""## 3. Extraction d'un "Speaker Embedding" réel pour une voix fluide

Pour obtenir une voix générée plus naturelle et fluide, nous allons extraire un "speaker embedding" à partir d'un fichier audio réel. Ce vecteur capture les caractéristiques vocales uniques d'un locuteur. Un embedding aléatoire (comme celui utilisé temporairement ci-dessus) produit une voix générique et moins fluide.

### 3.1 Téléchargement d'un fichier audio depuis Google Drive

Pour utiliser un fichier audio de Google Drive, la meilleure approche est de le télécharger d'abord dans l'environnement Colab. Cela garantit que `torchaudio.load` peut y accéder comme un fichier local. Nous utiliserons la bibliothèque `gdown` pour cela.

**Étapes :**

1.  **Obtenez l'ID du fichier Google Drive.** Si votre lien est du type `https://drive.google.com/file/d/FILE_ID/view?usp=share_link`, l'ID est `FILE_ID`.
2.  **Mettez à jour la variable `gdrive_file_id`** dans la cellule suivante.
3.  **Exécutez la cellule** pour télécharger le fichier.
"""

import gdown
import os

# L'ID de votre fichier Google Drive
# Extrayez l'ID de votre lien: https://drive.google.com/file/d/1kbUYpUkWmXAy8UTvZuN9GPug7F6nS_b6/view?usp=share_link
gdrive_file_id = '1kbUYpUkWmXAy8UTvZuN9GPug7F6nS_b6' # <-- REMPLACEZ CET ID !

# Nom du fichier une fois téléchargé dans Colab
local_audio_filename = 'my_speaker_audio.wav'
local_audio_file_path = os.path.join('/content/', local_audio_filename)

# Télécharger le fichier
try:
    gdown.download(id=gdrive_file_id, output=local_audio_file_path, quiet=False)
    print(f"Fichier téléchargé : {local_audio_file_path}")
except Exception as e:
    print(f"Erreur lors du téléchargement du fichier: {e}")
    print("Assurez-vous que le fichier est partagé via un lien et que l'ID est correct.")

"""### 3.2 Extraire l'embedding du locuteur du fichier audio"""

import torchaudio
from speechbrain.pretrained import EncoderClassifier

# Charger le modèle d'encodage de locuteur de SpeechBrain
# Ce modèle extrait les x-vectors, qui sont des types d'embeddings de locuteur.
# Le modèle est téléchargé la première fois, cela peut prendre un certain temps.
speaker_encoder = EncoderClassifier.from_hparams(source="speechbrain/spkrec-xvect-voxceleb", savedir="pretrained_models/speaker_encoder")

# --- Utilisez le chemin vers votre fichier audio téléchargé ---
# `local_audio_file_path` est défini dans la cellule précédente après le téléchargement.
audio_file_path_for_embedding = local_audio_file_path

# Charger le fichier audio
signal, fs = torchaudio.load(audio_file_path_for_embedding)

# Normaliser la fréquence d'échantillonnage si nécessaire (SpeechT5 attend 16kHz)
if fs != 16000:
    resampler = torchaudio.transforms.Resample(orig_freq=fs, new_freq=16000)
    signal = resampler(signal)

# Assurez-vous que le signal est mono et a une dimension de batch
# `torchaudio.load` retourne `(num_channels, num_samples)`
# `speechbrain` s'attend à `(batch_size, num_samples)`.
# Nous prenons le premier canal et ajoutons une dimension de batch.
signal = signal[0].unsqueeze(0) # Prend le premier canal (mono) et ajoute la dimension de batch

# Extraire le "speaker embedding"
with torch.no_grad():
    speaker_embedding = speaker_encoder.encode_batch(signal.to(device))

print(f"Speaker embedding généré avec succès de la forme : {speaker_embedding.shape}")

"""## 4. Exemples de génération de parole

Maintenant que les modèles sont chargés et que le "speaker embedding" est extrait, nous pouvons générer de la parole. N'oubliez pas d'utiliser le SSML (`<break time="Xms"/>`) pour contrôler la fluidité et le rythme de la voix.
"""

# Exemple 1 : Français (texte brut)
print("\n--- Français (texte brut) ---")
text_fr_plain = "Bonjour, bienvenue dans le modèle de synthèse vocale Wolof et Français."
generate_speech_from_text(text_fr_plain, speaker_embedding)

# Exemple 2 : Wolof (texte brut)
print("\n--- Wolof (texte brut) ---")
text_wolof_plain = "ñu ne ñoom ñooy nattukaay satélite yi"
generate_speech_from_text(text_wolof_plain, speaker_embedding)

# Exemple 3 : Français avec SSML (pauses)
print("\n--- Français avec SSML (pauses) ---")
ssml_text_fr = "Bonjour,<break time=\"750ms\"/> bienvenue dans le modèle de synthèse vocale Wolof et Français.<break time=\"1s\"/> J'espère que cela vous convient mieux."
generate_speech_from_text(ssml_text_fr, speaker_embedding, use_ssml=True)

# Exemple 4 : Wolof avec SSML (pauses)
print("\n--- Wolof avec SSML (pauses) ---")
ssml_text_wolof = "ñu ne ñoom ñooy nattukaay satélite yi.<break time=\"750ms\"/> Foo deuk la beug xam?"
generate_speech_from_text(ssml_text_wolof, speaker_embedding, use_ssml=True)

# Exemple 5 : Autre phrase en Wolof (texte brut)
print("\n--- Autre phrase en Wolof (texte brut) ---")
text_wolof_new = "damaa sonou eske meun naaa gnibi"
generate_speech_from_text(text_wolof_new, speaker_embedding)

!pip install transformers datasets torch

# Importe la bibliothèque pour charger les secrets Colab
from google.colab import userdata

# Charge le HF_TOKEN depuis les secrets de Colab
HF_TOKEN = userdata.get('HF_TOKEN')

# Vous pouvez maintenant utiliser HF_TOKEN directement ou la bibliothèque
# transformers le détectera automatiquement une fois qu'il sera chargé dans l'environnement.
# Si vous voulez le définir explicitement pour la session courante:
import os
os.environ['HF_TOKEN'] = HF_TOKEN

print("HF_TOKEN chargé avec succès depuis les secrets de Colab.")

import torch
from transformers import SpeechT5ForTextToSpeech, SpeechT5Processor, SpeechT5HifiGan
from datasets import load_dataset
from IPython.display import Audio, display

def load_speech_model(checkpoint="bilalfaye/speecht5_tts-wolof-v0.2", vocoder_checkpoint="microsoft/speecht5_hifigan"):
    """ Load the SpeechT5 model, processor, and vocoder for text-to-speech. """

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

    processor = SpeechT5Processor.from_pretrained(checkpoint)
    model = SpeechT5ForTextToSpeech.from_pretrained(checkpoint).to(device)
    vocoder = SpeechT5HifiGan.from_pretrained(vocoder_checkpoint).to(device)

    return processor, model, vocoder, device

# Load the model
processor, model, vocoder, device = load_speech_model()

# Temporarily use a random speaker embedding as Matthijs/cmu-arctic-xvectors
# is no longer supported and speechbrain/speaker-embeddings-cmu-arctic-xvectors was not found.
# For a specific speaker, you would typically generate an embedding from an audio file.
speaker_embedding = torch.randn(1, 512).to(device) # Generate a random 512-dimension embedding and move to device

def generate_speech_from_text(input_text, speaker_embedding=speaker_embedding, processor=processor, model=model, vocoder=vocoder, use_ssml=False):
    """ Generates speech from input text using SpeechT5 and HiFi-GAN vocoder.
        If use_ssml is True, input_text is treated as SSML.
        Example SSML for pauses: "<break time=\"500ms\"/>"
    """
    # SpeechT5Processor tokenizes the raw text, including SSML tags. The model then interprets them.
    inputs = processor(text=input_text, return_tensors="pt", padding=True, truncation=True, max_length=model.config.max_text_positions)
    inputs = {key: value.to(model.device) for key, value in inputs.items()}

    speech = model.generate(
        inputs["input_ids"],
        speaker_embeddings=speaker_embedding.to(model.device),
        vocoder=vocoder,
        num_beams=7,
        temperature=0.6,
        no_repeat_ngram_size=3,
        repetition_penalty=1.5,
    )

    speech = speech.detach().cpu().numpy()
    display(Audio(speech, rate=16000))

# Example usage French (plain text)
text_fr = "Bonjour, bienvenue dans le modèle de synthèse vocale Wolof et Français."
generate_speech_from_text(text_fr)

# Example usage Wolof (plain text)
text_wolof = "ñu ne ñoom ñooy nattukaay satélite yi"
generate_speech_from_text(text_wolof)

# Example usage French with SSML for pauses
ssml_text_fr = "Bonjour,<break time=\"750ms\"/> bienvenue dans le modèle de synthèse vocale Wolof et Français.<break time=\"1s\"/> J'espère que cela vous convient mieux."
generate_speech_from_text(ssml_text_fr, use_ssml=True)

# Example usage Wolof with SSML for pauses
ssml_text_wolof = "ñu ne ñoom ñooy nattukaay satélite yi.<break time=\"750ms\"/> Foo deuk la beug xam?"
generate_speech_from_text(ssml_text_wolof, use_ssml=True)



# Example usage Wolof
text = "foo deuk laa beug xam"
generate_speech_from_text(text)

"""### Améliorer la fluidité de la voix avec un "Speaker Embedding" réel

Le "speaker embedding" (ou encodage de locuteur) est un vecteur qui capture les caractéristiques uniques de la voix d'une personne. Lorsque nous utilisons un embedding aléatoire, le modèle SpeechT5 n'a pas d'informations sur les caractéristiques vocales d'un locuteur spécifique, ce qui conduit à une voix générée moins naturelle.

Pour obtenir une voix plus fluide, nous allons :

1.  **Installer les bibliothèques nécessaires :** `torchaudio` pour le traitement audio et `speechbrain` pour le modèle d'encodage de locuteur.
2.  **Charger un modèle d'encodage de locuteur :** Nous utiliserons un modèle pré-entraîné pour extraire le "speaker embedding" d'un fichier audio.
3.  **Fournir un fichier audio :** Vous devrez soit charger un fichier audio (par exemple, un enregistrement de votre propre voix ou un extrait d'une voix que vous souhaitez imiter), soit utiliser un fichier audio existant sur le système.
4.  **Extraire le "speaker embedding" :** Utiliser le modèle d'encodage pour obtenir le vecteur caractéristique de la voix à partir de votre fichier audio.
5.  **Utiliser ce "speaker embedding" avec SpeechT5 :** Injecter cet embedding dans le processus de génération vocale pour obtenir une voix plus naturelle.
"""

# Installer les bibliothèques nécessaires
!pip install torchaudio speechbrain

import torchaudio
from speechbrain.pretrained import EncoderClassifier

# Charger le modèle d'encodage de locuteur
# Ce modèle extrait les x-vectors, qui sont des types d'embeddings de locuteur.
# Le modèle est téléchargé la première fois, cela peut prendre un certain temps.
speaker_encoder = EncoderClassifier.from_hparams(source="speechbrain/spkrec-xvect-voxceleb", savedir="pretrained_models/speaker_encoder")

# --- IMPORTANT : Fournissez ici le chemin vers votre fichier audio ---
# Si vous n'avez pas de fichier audio, vous pouvez en enregistrer un court
# (quelques secondes) ou utiliser un exemple disponible publiquement.
# Par exemple: /content/Wolof-TTS/data/audio/audio_example.wav
audio_file_path = "./audio.wav"  # <--- REMPLACEZ CE CHEMIN !

# Charger le fichier audio
signal, fs = torchaudio.load(audio_file_path)

# Normaliser la fréquence d'échantillonnage si nécessaire (SpeechT5 attend 16kHz)
if fs != 16000:
    resampler = torchaudio.transforms.Resample(orig_freq=fs, new_freq=16000)
    signal = resampler(signal)

# Assurez-vous que le signal est mono et a une dimension de batch
# torchaudio.load retourne (num_channels, num_samples)
# Nous voulons (batch_size, num_samples) pour speechbrain.
# Nous prenons le premier canal et ajoutons une dimension de batch.
signal = signal[0].unsqueeze(0) # Prend le premier canal et ajoute la dimension de batch

# Extraire le "speaker embedding"
with torch.no_grad():
    speaker_embedding_new = speaker_encoder.encode_batch(signal.to(device))

print(f"Speaker embedding généré avec succès de la forme : {speaker_embedding_new.shape}")

# Mettre à jour la variable globale speaker_embedding pour l'utiliser dans la fonction generate_speech_from_text
speaker_embedding = speaker_embedding_new

# Exemple usage French avec le nouvel embedding
text = "Bonjour, bienvenue dans le modèle de synthèse vocale Wolof et Français."
generate_speech_from_text(text)

# Exemple usage Wolof avec le nouvel embedding
text = "damaa sonou eske meun naaa gnibi"
generate_speech_from_text(text)

"""### Utiliser un fichier audio de Google Drive dans Colab

Pour utiliser un fichier de Google Drive, la meilleure approche est de le télécharger d'abord dans l'environnement Colab. Cela garantit que `torchaudio.load` peut y accéder comme un fichier local. Nous utiliserons la bibliothèque `gdown` pour cela.

**Étapes :**

1.  **Installez `gdown`** (si ce n'est pas déjà fait).
2.  **Obtenez l'ID du fichier Google Drive.** Si votre lien est du type `https://drive.google.com/file/d/FILE_ID/view?usp=share_link`, l'ID est `FILE_ID`.
3.  **Utilisez `gdown.download`** pour télécharger le fichier. Assurez-vous que le fichier est partagé publiquement ou que vous êtes authentifié sur Drive dans Colab (bien que `gdown` puisse souvent contourner les problèmes d'authentification pour les fichiers partagés via un lien).
4.  **Mettez à jour le chemin `audio_file_path`** dans la cellule `91290c38` pour qu'il pointe vers le fichier téléchargé localement.
"""

# Installer gdown pour télécharger des fichiers depuis Google Drive
!pip install gdown

import gdown
import os

# L'ID de votre fichier Google Drive
# Extrayez l'ID de votre lien: https://drive.google.com/file/d/1kbUYpUkWmXAy8UTvZuN9GPug7F6nS_b6/view?usp=share_link
gdrive_file_id = '1kbUYpUkWmXAy8UTvZuN9GPug7F6nS_b6'

# Nom du fichier une fois téléchargé dans Colab
local_audio_filename = 'my_audio_file.wav'
local_audio_file_path = os.path.join('/content/', local_audio_filename)

# Télécharger le fichier
try:
    gdown.download(id=gdrive_file_id, output=local_audio_file_path, quiet=False)
    print(f"Fichier téléchargé : {local_audio_file_path}")
except Exception as e:
    print(f"Erreur lors du téléchargement du fichier: {e}")
    print("Assurez-vous que le fichier est partagé via un lien et que l'ID est correct.")

# Mettre à jour la variable audio_file_path avec le chemin local
# Nous allons modifier la cellule 91290c38 pour utiliser ce nouveau chemin.
# Pour l'instant, stockons-le dans une variable pour les prochaines étapes.
updated_audio_file_path = local_audio_file_path



"""Après avoir exécuté la cellule ci-dessus et remplacé `"/path/to/your/audio_file.wav"` par le chemin de votre fichier audio, le "speaker embedding" global sera mis à jour. Les appels suivants à `generate_speech_from_text` utiliseront ce nouvel embedding, ce qui devrait améliorer considérablement la fluidité et la naturalité de la voix générée.

## Configuration du HF_TOKEN

Pour définir votre `HF_TOKEN` et éviter les avertissements de Hugging Face :

1.  **Obtenez un jeton (token) Hugging Face :**
    *   Rendez-vous sur [Hugging Face Settings/Tokens](https://huggingface.co/settings/tokens).
    *   Créez un nouveau jeton d'accès avec le rôle `Read` (lecture).

2.  **Ajoutez le jeton aux secrets de Colab :**
    *   Dans Colab, cliquez sur l'icône "🔑" (Secrets) dans le panneau de gauche.
    *   Cliquez sur `+ New secret`.
    *   Pour le champ `Name`, entrez `HF_TOKEN` (cela doit correspondre au nom que le code cherchera).
    *   Pour le champ `Value`, collez le jeton que vous avez copié depuis Hugging Face.
    *   Assurez-vous que l'option `Notebook access` est cochée pour ce secret.

3.  **Chargez le jeton dans votre code :**
    *   Le code suivant montre comment charger le `HF_TOKEN` depuis les secrets de Colab. Une fois chargé, la bibliothèque `transformers` l'utilisera automatiquement pour vos requêtes.
"""

